// API endpoint for user profile statistics
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export default async function handler(req, res) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { userId } = req.query;

    if (!userId) {
      return res.status(400).json({
        success: false,
        message: 'User ID required'
      });
    }

    // Get user data
    const user = await prisma.user.findUnique({
      where: { userId }
    });

    if (!user) {
      return res.status(404).json({
        success: false,
        message: 'User not found'
      });
    }

    // Count images generated by this user
    const totalImages = await prisma.generation.count({
      where: {
        userId,
        type: 'image'
      }
    });

    // Count videos generated by this user
    const totalVideos = await prisma.generation.count({
      where: {
        userId,
        type: 'video'
      }
    });

    // Get all transactions (to calculate total money spent)
    const transactions = await prisma.transaction.findMany({
      where: { userId }
    });

    // Calculate total money spent (exclude free credits)
    let totalMoneySpent = 0;
    let totalCreditsAdded = 0;

    transactions.forEach(transaction => {
      const isFreeCredit = transaction.packageName?.toLowerCase().includes('free') ||
                           transaction.packageName?.includes('ฟรี') ||
                           transaction.packageName?.includes('เคลม');

      if (!isFreeCredit && transaction.status === 'completed') {
        // Count as actual money spent
        // Assuming each credit costs a certain amount
        // We'll use the transaction amount as credits added from payment
        totalMoneySpent += transaction.amount || 0;
        totalCreditsAdded += transaction.amount || 0;
      }
    });

    return res.status(200).json({
      success: true,
      stats: {
        totalImages,
        totalVideos,
        totalGenerated: totalImages + totalVideos,
        creditsUsed: user.creditsUsed || 0,
        creditsRemaining: user.credits || 0,
        totalCreditsAdded,  // Total credits from paid purchases
        totalMoneySpent     // Same as totalCreditsAdded for now
      }
    });

  } catch (error) {
    console.error('Error fetching profile stats:', error);
    return res.status(500).json({
      success: false,
      message: 'Internal server error',
      error: error.message
    });
  } finally {
    await prisma.$disconnect();
  }
}
